spring.application.name=backend

# サーバーのポート番号（Reactと被らないように8080）
server.port=8080

# データベース接続設定
# 'pokemon_db' の部分は、あらかじめPostgreSQLで作っておいたDB名に変えてください
spring.datasource.url=jdbc:postgresql://localhost:5432/pokemon_db
spring.datasource.username=postgres
spring.datasource.password=Esfgasbcd732!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernateの設定
# updateにすると、Javaのコードに合わせて自動でテーブルを作ったり更新したりしてくれます
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 再読み込みで更新でき江うようにする
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true